### ISSUE TITLE
Add clusterwise segmentation

### ISSUE THREAD

**Issue by martino-vic** [martino-vic/rtbwestoldturkic#6]
Currently segmentation happens through [orthography.py](https://github.com/martino-vic/ronatasbertawot/blob/main/raw/misc/makeortho.py). All it would take to apply the clusterwise segmentation is `from ipatok import clusterise` and to replace `tokenise` with `clusterise` in [line 12](https://github.com/martino-vic/ronatasbertawot/blob/main/raw/misc/makeortho.py#L12). But I don't know how to make that column appear in forms.csv eventually

**Comment by LinguList** [comment]
See my PR #8 on this ;)

**Comment by martino-vic** [comment]
Has worked out fine, so I'm close this issue now
